---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-edge
  labels:
    app: point-of-sale
    app.kubernetes.io/part-of: pos
    app.openshift.io/runtime: camel  
spec:
  selector:
    matchLabels:
      app: camel-edge
  template:
    metadata:
      labels:
        app: camel-edge
    spec:
      containers:
      - name: camel-edge
        image: quay.io/redhatintegration/camel-edge:1.0.0
        env:
        - name: MQTT_URL
          value: tcp://edge-mqtt-0-svc:1883
        - name: PRICE_URL
          value: camel-price-svc:8080
        - name: S3_ACCESS_KEY
          value: <AWS_ACCESSS_KEY_ID>
        - name: S3_SECRET_KEY
          value: <AWS_SECRET_ACCESS_KEY>
        - name: S3_ENDPOINT_URL
          value: http://s3.openshift-storage.svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: camel-edge-svc
spec:
  selector:
    app: camel-edge
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: camel
spec:
  to:
    kind: Service
    name: camel-edge-svc
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
...