---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: runasanyuid
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
subjects:
  - kind: ServiceAccount
    name: runasanyuid
    namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ksql
  name: ksql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksql
  template:
    metadata:
      labels:
        app: ksql
    spec:
      containers:
      - env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: PLAINTEXT://edge-kafka-bootstrap:9092
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
          value: "true"
        - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
          value: "true"
        image: confluentinc/ksqldb-server:latest
        name: ksqldb-server
        ports:
        - containerPort: 8088
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ksql
  name: ksql
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: ksql
  type: ClusterIP
...