---
- name: Evaluate edge namespace if not exists
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ edge_namespace | default('edge') }}"
    state: present

- name: Evaluate Camel Price deployment
  k8s:
    namespace: "{{ edge_namespace | default('edge') }}"
    state: present
    resource_definition: "{{ lookup('template', 'camel-price-deployment.yaml.j2') }}"

- name: Evaluate Camel Edge deployment
  k8s:
    namespace: "{{ edge_namespace | default('edge') }}"
    state: present
    resource_definition: "{{ lookup('template', 'camel-edge-deployment.yaml.j2') }}"
